[versions]
agp = "8.3.0"
banner = "2.2.3"
cardview = "1.0.0"
glide = "4.15.1"
kotlin = "1.9.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.7.0"
composeBom = "2023.08.00"
appcompat = "1.6.1"
material = "1.11.0"
coroutines = "1.6.1"
materialVersion = "1.4.0"
okhttp3Interceptor = "3.6.0"
okhttp3 = "3.12.0"
retrofit = "2.6.0"
databindingRuntime = "8.3.1"
rxlifecycleComponents = "2.2.2"
constraintlayout = "2.1.4"
utilcodex = "1.31.0"
viewpager2 = "1.0.0"

[libraries]
#api 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1' //协程
#api 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.1'
#implementation 'io.github.youth5201314:banner:2.2.3'
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
banner = { module = "io.github.youth5201314:banner", version.ref = "banner" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
material-v140 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
org-jetbrains-kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
org-jetbrains-kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
rxlifecycle-components = { module = "com.trello.rxlifecycle2:rxlifecycle-components", version.ref = "rxlifecycleComponents" }
squareup-okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3Interceptor" }
squareup-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
squareup-retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
squareup-retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
squareup-retrofit2-adapter-rxjava2 = { group = "com.squareup.retrofit2", name = "adapter-rxjava2", version.ref = "retrofit" }
androidx-databinding-runtime = { group = "androidx.databinding", name = "databinding-runtime", version.ref = "databindingRuntime" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }

#api 'com.squareup.okhttp3:logging-interceptor:3.6.0'
#api 'com.squareup.okhttp3:okhttp:3.12.0'
#api 'com.squareup.retrofit2:retrofit:2.6.0'
#api 'com.squareup.retrofit2:converter-gson:2.6.0'
#api 'com.squareup.retrofit2:adapter-rxjava2:2.6.0'

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

